#!/bin/sh
# Generate sc_version.h with version, git hash, and build date.
# Usage: gen_version.sh <version> <output_header>
# Only overwrites if content changed (avoids unnecessary rebuilds).

set -e

VERSION="$1"
OUTPUT="$2"

if [ -z "$VERSION" ] || [ -z "$OUTPUT" ]; then
    echo "Usage: $0 <version> <output_header>" >&2
    exit 1
fi

# Git hash (short, 8 chars) — fallback to "unknown" outside a repo
if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
    GIT_HASH=$(git rev-parse --short=8 HEAD 2>/dev/null || echo "unknown")
else
    GIT_HASH="unknown"
fi

# UTC build timestamp
BUILD_DATE=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

# Generate header content
CONTENT="#ifndef SC_VERSION_H
#define SC_VERSION_H
/* Auto-generated by gen_version.sh -- do not edit */
#define SC_VERSION      \"${VERSION}\"
#define SC_GIT_HASH     \"${GIT_HASH}\"
#define SC_BUILD_DATE   \"${BUILD_DATE}\"
#define SC_VERSION_FULL \"${VERSION}+${GIT_HASH}\"
#endif /* SC_VERSION_H */
"

# Only write if content changed (compare without build date for stability,
# but we always regenerate since the date changes — cmake handles dep tracking)
if [ -f "$OUTPUT" ]; then
    OLD=$(cat "$OUTPUT" 2>/dev/null || true)
    if [ "$OLD" = "$CONTENT" ]; then
        exit 0
    fi
fi

mkdir -p "$(dirname "$OUTPUT")"
printf '%s' "$CONTENT" > "$OUTPUT"
