#!/usr/bin/env python3
"""Generate sc_features.h and sc_features.cmake from Kconfig + .config.

Usage: kconfig_genconfig.py <kconfig> <dotconfig> <header_out> <cmake_out>

If <dotconfig> does not exist, all-defaults are used.
CLI -D overrides: any extra KEY=VALUE args override the .config value.
"""
import sys
import os

FEATURE_SYMS = [
    "SC_ENABLE_TELEGRAM",
    "SC_ENABLE_DISCORD",
    "SC_ENABLE_IRC",
    "SC_ENABLE_SLACK",
    "SC_ENABLE_WEB",
    "SC_ENABLE_GIT",
    "SC_ENABLE_WEB_TOOLS",
    "SC_ENABLE_VOICE",
    "SC_ENABLE_STREAMING",
    "SC_ENABLE_CRON",
    "SC_ENABLE_SPAWN",
    "SC_ENABLE_HEARTBEAT",
    "SC_ENABLE_BACKGROUND",
    "SC_ENABLE_MCP",
    "SC_ENABLE_MEMORY_SEARCH",
    "SC_ENABLE_VAULT",
    "SC_ENABLE_UPDATER",
]


def main():
    if len(sys.argv) < 5:
        print(f"Usage: {sys.argv[0]} <kconfig> <dotconfig> <header> <cmake> [KEY=VAL ...]",
              file=sys.stderr)
        sys.exit(1)

    kconfig_path = sys.argv[1]
    dotconfig_path = sys.argv[2]
    header_path = sys.argv[3]
    cmake_path = sys.argv[4]
    overrides = {}
    for arg in sys.argv[5:]:
        if "=" in arg:
            k, v = arg.split("=", 1)
            overrides[k] = v

    try:
        from kconfiglib import Kconfig
    except ImportError:
        print("ERROR: kconfiglib not found. Install with: pip install kconfiglib",
              file=sys.stderr)
        sys.exit(1)

    # Suppress kconfiglib's own output
    os.environ["KCONFIG_CONFIG"] = dotconfig_path
    kconf = Kconfig(kconfig_path, suppress_traceback=True)

    if os.path.isfile(dotconfig_path):
        kconf.load_config(dotconfig_path)
    else:
        # No .config — use all defaults (everything ON)
        pass

    # Apply CLI overrides: -DSC_ENABLE_X=ON/OFF
    for sym_name, val in overrides.items():
        sym = kconf.syms.get(sym_name)
        if sym is not None:
            if val.upper() in ("ON", "Y", "YES", "1", "TRUE"):
                sym.set_value(2)  # y
            elif val.upper() in ("OFF", "N", "NO", "0", "FALSE"):
                sym.set_value(0)  # n

    # Collect values
    values = {}
    for sym_name in FEATURE_SYMS:
        sym = kconf.syms.get(sym_name)
        if sym is not None:
            values[sym_name] = (sym.tri_value == 2)  # y = 2
        else:
            values[sym_name] = True  # default ON if not found

    # Write sc_features.h
    lines = [
        "#ifndef SC_FEATURES_H",
        "#define SC_FEATURES_H",
        "/* Auto-generated by kconfig_genconfig.py -- do not edit */",
    ]
    for sym_name in FEATURE_SYMS:
        val = 1 if values[sym_name] else 0
        lines.append(f"#define {sym_name} {val}")
    lines.append("#endif /* SC_FEATURES_H */")
    lines.append("")

    header_content = "\n".join(lines)
    _write_if_changed(header_path, header_content)

    # Write sc_features.cmake
    cmake_lines = ["# Auto-generated by kconfig_genconfig.py -- do not edit"]
    for sym_name in FEATURE_SYMS:
        cmake_val = "ON" if values[sym_name] else "OFF"
        cmake_lines.append(f'set({sym_name} {cmake_val})')
    cmake_lines.append("")

    cmake_content = "\n".join(cmake_lines)
    _write_if_changed(cmake_path, cmake_content)

    # Summary
    enabled = [s for s in FEATURE_SYMS if values[s]]
    disabled = [s for s in FEATURE_SYMS if not values[s]]
    print(f"kconfig: {len(enabled)}/{len(FEATURE_SYMS)} features enabled", file=sys.stderr)
    if disabled:
        print(f"kconfig: disabled: {', '.join(disabled)}", file=sys.stderr)


def _write_if_changed(path, content):
    """Only write if content differs — avoids unnecessary rebuilds."""
    if os.path.isfile(path):
        with open(path, "r") as f:
            if f.read() == content:
                return
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


if __name__ == "__main__":
    main()
