#ifndef SC_WORKSPACE_H
#define SC_WORKSPACE_H

#include <stddef.h>

/* Embedded workspace file */
typedef struct {
    const char *name;       /* Relative path (e.g., "AGENTS.md") */
    const unsigned char *data;
    unsigned int size;
} sc_workspace_file_t;

/* Generated by embed_workspace.sh */
extern const sc_workspace_file_t sc_workspace_files[];
extern const int sc_workspace_file_count;

/* Extract embedded workspace files to target directory.
 * Only writes files that don't already exist. Returns 0 on success. */
int sc_workspace_extract(const char *target_dir);

#endif /* SC_WORKSPACE_H */
